services:
  - type: web
    name: n8n
    env: docker
    plan: free
    branch: master
    repo: https://github.com/n8n-io/n8n
    dockerfilePath: Dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: Prykhorchuk_books
      - key: N8N_BASIC_AUTH_PASSWORD
        value: ZarabotokForDreams2025
